<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ticketing.Domain\Ticketing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EventManagement\" />
    <Folder Include="CheckinManagement\" />
    <Folder Include="Shared\" />
    <Folder Include="RefundManagement\" />
    <Folder Include="PaymentManagement\" />
    <Folder Include="TicketBookingManagement\" />
    <Folder Include="TicketCategoryManagement\" />
  </ItemGroup>

</Project>
