<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CheckinManagement\**" />
    <Compile Remove="PaymentManagement\**" />
    <Compile Remove="RefundManagement\**" />
    <Compile Remove="TicketCategoryManagement\**" />
    <EmbeddedResource Remove="CheckinManagement\**" />
    <EmbeddedResource Remove="PaymentManagement\**" />
    <EmbeddedResource Remove="RefundManagement\**" />
    <EmbeddedResource Remove="TicketCategoryManagement\**" />
    <None Remove="CheckinManagement\**" />
    <None Remove="PaymentManagement\**" />
    <None Remove="RefundManagement\**" />
    <None Remove="TicketCategoryManagement\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ticketing.Domain\Ticketing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
