<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TicketCategoryManagement\**" />
    <EmbeddedResource Remove="TicketCategoryManagement\**" />
    <None Remove="TicketCategoryManagement\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ticketing.Domain\Ticketing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CheckinManagement\" />
    <Folder Include="DTOs\" />
    <Folder Include="Queries\" />
    <Folder Include="RefundManagement\" />
    <Folder Include="PaymentManagement\" />
  </ItemGroup>

</Project>
